### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ghost**
This modified version does has a face tracking and a pedestrian tracking example. Both examples only run at very low frame rates at this point.

### CODE REVIEW

**Comment by genekogan** [comment]
thanks! i just tried these out, look very good. i would maybe just want to clean up the code a bit. 

the face-tracking example though does run kind of slow, have you compared it to ofxFaceTracker? wondering if it's more accurate so more suitable for non-real-time detection...

**Comment by antimodular** [comment]
i certainly know and have worked with ofxFaceTracker before, which works well.
since ofxccv runs so slow i have not compared it a lot to ofxFaceTracker. my sense is that it can detect smaller faces, but is not a lot better for rotated faces.

let me know what part of the code you think needs cleaning and if you want me to take some of this on or give it your own twist.

**Comment by genekogan** [comment]
i think just getting rid of the commented/unused code to keep things clean, also i think we'll want to add the necessary data files (face.sqlite and the pedestrian file) to the download script.

also, about facetracking more generally, there's a thread on [ofxFaceTracker](https://github.com/kylemcdonald/ofxFaceTracker/issues/117) about using the latest dlib which seems to have super fast and robust facetracking. [ofxLearn](https://github.com/genekogan/ofxLearn) is built on top of dlib (older version) so i've been meaning to try, just haven't made the time yet. check out the links cited in the first thread -- really impressive stuff.

**Comment by antimodular** [comment]
my new commit to my github has the files included. not sure if i have to post a new pull request?

i can go over the code again and remove all unnecessary commands and old code, in the next couple of days.

also, we have ofxDLib working with face tracking example:
https://github.com/roymacdonald/ofxDLib

**Comment by genekogan** [comment]
oh i see yeah. they are small enough to package with the library.

wow, i didn't see ofxDLib.  looks great! but i don't think it's using the same implementation as the one referenced above, and to my eyes [doesn't track as well as ofxFaceTracker](https://github.com/roymacdonald/ofxDLib/issues/3).

let's let kyle comment, and we can get to merging.

**Comment by kylemcdonald** [comment]
this generally looks good, but it will need some cleaning. if either of you want to go for it, @genekogan you should feel free to merge it after:
- the comments are cleaned up
- readme is cleaned up
- commits are squashed to one commit (optional, but helpful)
- remove `#ifdef USE_VIDEO` parts, this is usually left as exercise for user
- screenshots are either converted to jpg (to avoid unnecessary repo bloat) or removed completely (better). adding a screenshot to the PR is better than adding it to the repo.

**Comment by antimodular** [comment]
-cleaned the comments out
-cleaned the read me
-don't know how to squash things
-removed #ifdef
-converted screenshots to jpg

**Comment by kylemcdonald** [comment]
thanks! i'll take care of the rest.

**Comment by kylemcdonald** [comment]
i just merged it, but unfortunately the easiest way was with a single commit that does not include you in the history. i added antimodular to the readme and in the commit message, let me know if there's anything else i can do. thanks for the PR!

**Pull request closed without merging**
